// Action type constants
export const ACTIONS = {
  NAVIGATE: 'NAVIGATE',
  COMPLETE_ONBOARDING: 'COMPLETE_ONBOARDING',
  START_PROGRAM: 'START_PROGRAM',
  ADVANCE_DAY: 'ADVANCE_DAY',
  LOG_QUEST_COMPLETION: 'LOG_QUEST_COMPLETION',
  SHOW_GUILT: 'SHOW_GUILT',
  SNOOZE_GUILT: 'SNOOZE_GUILT',
  RECORD_GUILT_MESSAGE: 'RECORD_GUILT_MESSAGE',
  GIVE_UP_TODAY: 'GIVE_UP_TODAY',
  ABANDON_PROGRAM: 'ABANDON_PROGRAM',
  SAVE_SETTINGS: 'SAVE_SETTINGS',
  LOCK_MILESTONE: 'LOCK_MILESTONE',
}
